-- Skip indexes and the primary key must select the rows the comparison selects. A `FixedString` compares zero-padded:
-- an index looks up the stored value equal to the constant, and declines a constant that equals several stored values.
-- Each line: index, predicate, rows with the index, whether that equals the rows without it.

SET allow_experimental_full_text_index = 1;

DROP TABLE IF EXISTS tab_s_primary_key;
CREATE TABLE tab_s_primary_key (v String) ENGINE = MergeTree ORDER BY v SETTINGS index_granularity = 1;
INSERT INTO tab_s_primary_key SELECT arrayJoin(['ab', 'ab\0', 'ab\0\0', 'zz']);
DROP TABLE IF EXISTS tab_s_minmax;
CREATE TABLE tab_s_minmax (k UInt32, v String, INDEX idx v TYPE minmax GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_minmax SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));
DROP TABLE IF EXISTS tab_s_set;
CREATE TABLE tab_s_set (k UInt32, v String, INDEX idx v TYPE set(0) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_set SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));
DROP TABLE IF EXISTS tab_s_bloom_filter;
CREATE TABLE tab_s_bloom_filter (k UInt32, v String, INDEX idx v TYPE bloom_filter GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_bloom_filter SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));
DROP TABLE IF EXISTS tab_s_tokenbf_v1;
CREATE TABLE tab_s_tokenbf_v1 (k UInt32, v String, INDEX idx v TYPE tokenbf_v1(512, 2, 0) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_tokenbf_v1 SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));
DROP TABLE IF EXISTS tab_s_ngrambf_v1;
CREATE TABLE tab_s_ngrambf_v1 (k UInt32, v String, INDEX idx v TYPE ngrambf_v1(2, 512, 2, 0) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_ngrambf_v1 SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));
DROP TABLE IF EXISTS tab_s_text_array;
CREATE TABLE tab_s_text_array (k UInt32, v String, INDEX idx v TYPE text(tokenizer = array) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_text_array SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));
DROP TABLE IF EXISTS tab_s_text_splitByNonAlpha;
CREATE TABLE tab_s_text_splitByNonAlpha (k UInt32, v String, INDEX idx v TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_s_text_splitByNonAlpha SELECT number, ['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1] FROM numbers(length(['ab', 'ab\0', 'ab\0\0', 'zz']));

SELECT '-- String column';
SELECT 'primary key', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v = toFixedString('ab', 2) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v = toFixedString('ab', 2);
SELECT 'minmax', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v = toFixedString('ab', 2);
SELECT 'set', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v = toFixedString('ab', 2);
SELECT 'bloom_filter', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v = toFixedString('ab', 2);
SELECT 'tokenbf_v1', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v = toFixedString('ab', 2);
SELECT 'ngrambf_v1', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v = toFixedString('ab', 2);
SELECT 'text_array', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v = toFixedString('ab', 2);
SELECT 'text_splitByNonAlpha', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v = toFixedString('ab', 2);
SELECT 'primary key', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN (toFixedString('ab', 2)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN (toFixedString('ab', 2));
SELECT 'minmax', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN (toFixedString('ab', 2));
SELECT 'set', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN (toFixedString('ab', 2));
SELECT 'bloom_filter', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN (toFixedString('ab', 2));
SELECT 'tokenbf_v1', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN (toFixedString('ab', 2));
SELECT 'ngrambf_v1', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN (toFixedString('ab', 2));
SELECT 'text_array', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN (toFixedString('ab', 2));
SELECT 'text_splitByNonAlpha', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 2));
SELECT 'primary key', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'minmax', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'set', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'bloom_filter', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'tokenbf_v1', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'ngrambf_v1', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'text_array', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'text_splitByNonAlpha', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'primary key', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v = toFixedString('ab', 4) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v = toFixedString('ab', 4);
SELECT 'minmax', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v = toFixedString('ab', 4);
SELECT 'set', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v = toFixedString('ab', 4);
SELECT 'bloom_filter', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v = toFixedString('ab', 4);
SELECT 'tokenbf_v1', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v = toFixedString('ab', 4);
SELECT 'ngrambf_v1', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v = toFixedString('ab', 4);
SELECT 'text_array', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v = toFixedString('ab', 4);
SELECT 'text_splitByNonAlpha', 'v = toFixedString(\'ab\', 4)', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v = toFixedString('ab', 4) SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v = toFixedString('ab', 4);
SELECT 'primary key', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN (toFixedString('ab', 4)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN (toFixedString('ab', 4));
SELECT 'minmax', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN (toFixedString('ab', 4));
SELECT 'set', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN (toFixedString('ab', 4));
SELECT 'bloom_filter', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN (toFixedString('ab', 4));
SELECT 'tokenbf_v1', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN (toFixedString('ab', 4));
SELECT 'ngrambf_v1', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN (toFixedString('ab', 4));
SELECT 'text_array', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN (toFixedString('ab', 4));
SELECT 'text_splitByNonAlpha', 'v IN (toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 4));
SELECT 'primary key', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'minmax', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'set', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'bloom_filter', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'tokenbf_v1', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'ngrambf_v1', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'text_array', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'text_splitByNonAlpha', 'v IN (SELECT toFixedString(\'ab\', 4))', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 4));
SELECT 'primary key', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v = 'ab' SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v = 'ab';
SELECT 'minmax', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v = 'ab';
SELECT 'set', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v = 'ab';
SELECT 'bloom_filter', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v = 'ab';
SELECT 'tokenbf_v1', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v = 'ab';
SELECT 'ngrambf_v1', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v = 'ab';
SELECT 'text_array', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v = 'ab';
SELECT 'text_splitByNonAlpha', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v = 'ab';
SELECT 'primary key', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN ('ab') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN ('ab');
SELECT 'minmax', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN ('ab');
SELECT 'set', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN ('ab');
SELECT 'bloom_filter', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN ('ab');
SELECT 'tokenbf_v1', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN ('ab');
SELECT 'ngrambf_v1', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN ('ab');
SELECT 'text_array', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN ('ab');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN ('ab');
SELECT 'primary key', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN (SELECT 'ab') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN (SELECT 'ab');
SELECT 'minmax', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN (SELECT 'ab');
SELECT 'set', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN (SELECT 'ab');
SELECT 'bloom_filter', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN (SELECT 'ab');
SELECT 'tokenbf_v1', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN (SELECT 'ab');
SELECT 'ngrambf_v1', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN (SELECT 'ab');
SELECT 'text_array', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN (SELECT 'ab');
SELECT 'text_splitByNonAlpha', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT 'ab');
SELECT 'primary key', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v = 'ab\0' SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v = 'ab\0';
SELECT 'minmax', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v = 'ab\0';
SELECT 'set', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v = 'ab\0';
SELECT 'bloom_filter', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v = 'ab\0';
SELECT 'tokenbf_v1', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v = 'ab\0';
SELECT 'ngrambf_v1', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v = 'ab\0';
SELECT 'text_array', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v = 'ab\0';
SELECT 'text_splitByNonAlpha', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v = 'ab\0';
SELECT 'primary key', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN ('ab\0') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN ('ab\0');
SELECT 'minmax', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN ('ab\0');
SELECT 'set', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN ('ab\0');
SELECT 'bloom_filter', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN ('ab\0');
SELECT 'tokenbf_v1', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN ('ab\0');
SELECT 'ngrambf_v1', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN ('ab\0');
SELECT 'text_array', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN ('ab\0');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN ('ab\0');
SELECT 'primary key', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN (SELECT 'ab\0') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN (SELECT 'ab\0');
SELECT 'minmax', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN (SELECT 'ab\0');
SELECT 'set', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN (SELECT 'ab\0');
SELECT 'bloom_filter', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN (SELECT 'ab\0');
SELECT 'tokenbf_v1', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN (SELECT 'ab\0');
SELECT 'ngrambf_v1', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN (SELECT 'ab\0');
SELECT 'text_array', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN (SELECT 'ab\0');
SELECT 'text_splitByNonAlpha', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN (SELECT 'ab\0');
SELECT 'primary key', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_primary_key WHERE v IN ('ab', 'zz') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_s_primary_key WHERE v IN ('ab', 'zz');
SELECT 'minmax', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_minmax WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_minmax WHERE v IN ('ab', 'zz');
SELECT 'set', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_set WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_set WHERE v IN ('ab', 'zz');
SELECT 'bloom_filter', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_bloom_filter WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_bloom_filter WHERE v IN ('ab', 'zz');
SELECT 'tokenbf_v1', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_tokenbf_v1 WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_tokenbf_v1 WHERE v IN ('ab', 'zz');
SELECT 'ngrambf_v1', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_ngrambf_v1 WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_ngrambf_v1 WHERE v IN ('ab', 'zz');
SELECT 'text_array', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_text_array WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_text_array WHERE v IN ('ab', 'zz');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_s_text_splitByNonAlpha WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_s_text_splitByNonAlpha WHERE v IN ('ab', 'zz');

DROP TABLE IF EXISTS tab_f_primary_key;
CREATE TABLE tab_f_primary_key (v FixedString(4)) ENGINE = MergeTree ORDER BY v SETTINGS index_granularity = 1;
INSERT INTO tab_f_primary_key SELECT arrayJoin(['ab', 'zz']);
DROP TABLE IF EXISTS tab_f_minmax;
CREATE TABLE tab_f_minmax (k UInt32, v FixedString(4), INDEX idx v TYPE minmax GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_minmax SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));
DROP TABLE IF EXISTS tab_f_set;
CREATE TABLE tab_f_set (k UInt32, v FixedString(4), INDEX idx v TYPE set(0) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_set SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));
DROP TABLE IF EXISTS tab_f_bloom_filter;
CREATE TABLE tab_f_bloom_filter (k UInt32, v FixedString(4), INDEX idx v TYPE bloom_filter GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_bloom_filter SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));
DROP TABLE IF EXISTS tab_f_tokenbf_v1;
CREATE TABLE tab_f_tokenbf_v1 (k UInt32, v FixedString(4), INDEX idx v TYPE tokenbf_v1(512, 2, 0) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_tokenbf_v1 SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));
DROP TABLE IF EXISTS tab_f_ngrambf_v1;
CREATE TABLE tab_f_ngrambf_v1 (k UInt32, v FixedString(4), INDEX idx v TYPE ngrambf_v1(2, 512, 2, 0) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_ngrambf_v1 SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));
DROP TABLE IF EXISTS tab_f_text_array;
CREATE TABLE tab_f_text_array (k UInt32, v FixedString(4), INDEX idx v TYPE text(tokenizer = array) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_text_array SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));
DROP TABLE IF EXISTS tab_f_text_splitByNonAlpha;
CREATE TABLE tab_f_text_splitByNonAlpha (k UInt32, v FixedString(4), INDEX idx v TYPE text(tokenizer = splitByNonAlpha) GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_f_text_splitByNonAlpha SELECT number, ['ab', 'zz'][number + 1] FROM numbers(length(['ab', 'zz']));

SELECT '-- FixedString(4) column';
SELECT 'primary key', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v = toFixedString('ab', 2) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v = toFixedString('ab', 2);
SELECT 'minmax', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v = toFixedString('ab', 2);
SELECT 'set', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v = toFixedString('ab', 2);
SELECT 'bloom_filter', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v = toFixedString('ab', 2);
SELECT 'tokenbf_v1', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v = toFixedString('ab', 2);
SELECT 'ngrambf_v1', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v = toFixedString('ab', 2);
SELECT 'text_array', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v = toFixedString('ab', 2);
SELECT 'text_splitByNonAlpha', 'v = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v = toFixedString('ab', 2);
SELECT 'primary key', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (toFixedString('ab', 2)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (toFixedString('ab', 2));
SELECT 'minmax', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (toFixedString('ab', 2));
SELECT 'set', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (toFixedString('ab', 2));
SELECT 'bloom_filter', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (toFixedString('ab', 2));
SELECT 'tokenbf_v1', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (toFixedString('ab', 2));
SELECT 'ngrambf_v1', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (toFixedString('ab', 2));
SELECT 'text_array', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (toFixedString('ab', 2));
SELECT 'text_splitByNonAlpha', 'v IN (toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 2));
SELECT 'primary key', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'minmax', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'set', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'bloom_filter', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'tokenbf_v1', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'ngrambf_v1', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'text_array', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'text_splitByNonAlpha', 'v IN (SELECT toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 2));
SELECT 'primary key', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v = toFixedString('ab', 6) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v = toFixedString('ab', 6);
SELECT 'minmax', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v = toFixedString('ab', 6);
SELECT 'set', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v = toFixedString('ab', 6);
SELECT 'bloom_filter', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v = toFixedString('ab', 6);
SELECT 'tokenbf_v1', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v = toFixedString('ab', 6);
SELECT 'ngrambf_v1', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v = toFixedString('ab', 6);
SELECT 'text_array', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v = toFixedString('ab', 6);
SELECT 'text_splitByNonAlpha', 'v = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v = toFixedString('ab', 6);
SELECT 'primary key', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (toFixedString('ab', 6)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (toFixedString('ab', 6));
SELECT 'minmax', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (toFixedString('ab', 6));
SELECT 'set', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (toFixedString('ab', 6));
SELECT 'bloom_filter', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (toFixedString('ab', 6));
SELECT 'tokenbf_v1', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (toFixedString('ab', 6));
SELECT 'ngrambf_v1', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (toFixedString('ab', 6));
SELECT 'text_array', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (toFixedString('ab', 6));
SELECT 'text_splitByNonAlpha', 'v IN (toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (toFixedString('ab', 6));
SELECT 'primary key', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'minmax', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'set', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'bloom_filter', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'tokenbf_v1', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'ngrambf_v1', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'text_array', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'text_splitByNonAlpha', 'v IN (SELECT toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT toFixedString('ab', 6));
SELECT 'primary key', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v = 'ab' SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v = 'ab';
SELECT 'minmax', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v = 'ab';
SELECT 'set', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v = 'ab';
SELECT 'bloom_filter', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v = 'ab';
SELECT 'tokenbf_v1', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v = 'ab';
SELECT 'ngrambf_v1', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v = 'ab';
SELECT 'text_array', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v = 'ab';
SELECT 'text_splitByNonAlpha', 'v = \'ab\'', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v = 'ab';
SELECT 'primary key', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN ('ab') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN ('ab');
SELECT 'minmax', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN ('ab');
SELECT 'set', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN ('ab');
SELECT 'bloom_filter', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN ('ab');
SELECT 'tokenbf_v1', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN ('ab');
SELECT 'ngrambf_v1', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN ('ab');
SELECT 'text_array', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN ('ab');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab');
SELECT 'primary key', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (SELECT 'ab') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (SELECT 'ab');
SELECT 'minmax', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (SELECT 'ab');
SELECT 'set', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (SELECT 'ab');
SELECT 'bloom_filter', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (SELECT 'ab');
SELECT 'tokenbf_v1', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (SELECT 'ab');
SELECT 'ngrambf_v1', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (SELECT 'ab');
SELECT 'text_array', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (SELECT 'ab');
SELECT 'text_splitByNonAlpha', 'v IN (SELECT \'ab\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT 'ab') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT 'ab');
SELECT 'primary key', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v = 'ab\0' SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v = 'ab\0';
SELECT 'minmax', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v = 'ab\0';
SELECT 'set', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v = 'ab\0';
SELECT 'bloom_filter', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v = 'ab\0';
SELECT 'tokenbf_v1', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v = 'ab\0';
SELECT 'ngrambf_v1', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v = 'ab\0';
SELECT 'text_array', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v = 'ab\0';
SELECT 'text_splitByNonAlpha', 'v = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v = 'ab\0';
SELECT 'primary key', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN ('ab\0') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN ('ab\0');
SELECT 'minmax', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN ('ab\0');
SELECT 'set', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN ('ab\0');
SELECT 'bloom_filter', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN ('ab\0');
SELECT 'tokenbf_v1', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN ('ab\0');
SELECT 'ngrambf_v1', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN ('ab\0');
SELECT 'text_array', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN ('ab\0');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab\0');
SELECT 'primary key', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (SELECT 'ab\0') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (SELECT 'ab\0');
SELECT 'minmax', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (SELECT 'ab\0');
SELECT 'set', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (SELECT 'ab\0');
SELECT 'bloom_filter', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (SELECT 'ab\0');
SELECT 'tokenbf_v1', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (SELECT 'ab\0');
SELECT 'ngrambf_v1', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (SELECT 'ab\0');
SELECT 'text_array', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (SELECT 'ab\0');
SELECT 'text_splitByNonAlpha', 'v IN (SELECT \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT 'ab\0');
SELECT 'primary key', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v = 'ab\0\0\0\0' SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v = 'ab\0\0\0\0';
SELECT 'minmax', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v = 'ab\0\0\0\0';
SELECT 'set', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v = 'ab\0\0\0\0';
SELECT 'bloom_filter', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v = 'ab\0\0\0\0';
SELECT 'tokenbf_v1', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v = 'ab\0\0\0\0';
SELECT 'ngrambf_v1', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v = 'ab\0\0\0\0';
SELECT 'text_array', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v = 'ab\0\0\0\0';
SELECT 'text_splitByNonAlpha', 'v = \'ab\\0\\0\\0\\0\'', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v = 'ab\0\0\0\0' SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v = 'ab\0\0\0\0';
SELECT 'primary key', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN ('ab\0\0\0\0') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN ('ab\0\0\0\0');
SELECT 'minmax', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN ('ab\0\0\0\0');
SELECT 'set', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN ('ab\0\0\0\0');
SELECT 'bloom_filter', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN ('ab\0\0\0\0');
SELECT 'tokenbf_v1', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN ('ab\0\0\0\0');
SELECT 'ngrambf_v1', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN ('ab\0\0\0\0');
SELECT 'text_array', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN ('ab\0\0\0\0');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab\0\0\0\0');
SELECT 'primary key', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'minmax', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'set', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'bloom_filter', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'tokenbf_v1', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'ngrambf_v1', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'text_array', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'text_splitByNonAlpha', 'v IN (SELECT \'ab\\0\\0\\0\\0\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT 'ab\0\0\0\0') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN (SELECT 'ab\0\0\0\0');
SELECT 'primary key', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_primary_key WHERE v IN ('ab', 'zz') SETTINGS use_primary_key = 0, use_index_for_in_with_subqueries = 0) FROM tab_f_primary_key WHERE v IN ('ab', 'zz');
SELECT 'minmax', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_minmax WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_minmax WHERE v IN ('ab', 'zz');
SELECT 'set', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_set WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_set WHERE v IN ('ab', 'zz');
SELECT 'bloom_filter', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_bloom_filter WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_bloom_filter WHERE v IN ('ab', 'zz');
SELECT 'tokenbf_v1', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_tokenbf_v1 WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_tokenbf_v1 WHERE v IN ('ab', 'zz');
SELECT 'ngrambf_v1', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_ngrambf_v1 WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_ngrambf_v1 WHERE v IN ('ab', 'zz');
SELECT 'text_array', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_text_array WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_text_array WHERE v IN ('ab', 'zz');
SELECT 'text_splitByNonAlpha', 'v IN (\'ab\', \'zz\')', count() AS c, c = (SELECT count() FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab', 'zz') SETTINGS use_skip_indexes = 0) FROM tab_f_text_splitByNonAlpha WHERE v IN ('ab', 'zz');

SELECT '-- the index is still used for the stored value equal to the constant';
SELECT 'tab_f_primary_key', 'v = toFixedString(\'ab\', 6)', count() FROM tab_f_primary_key WHERE v = toFixedString('ab', 6) SETTINGS force_primary_key = 1;
SELECT 'tab_f_primary_key', 'v = \'ab\\0\'', count() FROM tab_f_primary_key WHERE v = 'ab\0' SETTINGS force_primary_key = 1;
SELECT 'tab_f_primary_key', 'v IN (SELECT toFixedString(\'ab\', 6))', count() FROM tab_f_primary_key WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS force_primary_key = 1;
SELECT 'tab_s_primary_key', 'v = \'ab\'', count() FROM tab_s_primary_key WHERE v = 'ab' SETTINGS force_primary_key = 1;
SELECT 'tab_f_bloom_filter', 'v = toFixedString(\'ab\', 6)', count() FROM tab_f_bloom_filter WHERE v = toFixedString('ab', 6) SETTINGS force_data_skipping_indices = 'idx';
SELECT 'tab_f_bloom_filter', 'v IN (SELECT toFixedString(\'ab\', 6))', count() FROM tab_f_bloom_filter WHERE v IN (SELECT toFixedString('ab', 6)) SETTINGS force_data_skipping_indices = 'idx';
SELECT 'tab_f_text_array', 'v = \'ab\\0\'', count() FROM tab_f_text_array WHERE v = 'ab\0' SETTINGS force_data_skipping_indices = 'idx';
SELECT 'tab_s_text_splitByNonAlpha', 'v = toFixedString(\'ab\', 4)', count() FROM tab_s_text_splitByNonAlpha WHERE v = toFixedString('ab', 4) SETTINGS force_data_skipping_indices = 'idx';
SELECT 'tab_s_tokenbf_v1', 'v = toFixedString(\'ab\', 4)', count() FROM tab_s_tokenbf_v1 WHERE v = toFixedString('ab', 4) SETTINGS force_data_skipping_indices = 'idx';

SELECT '-- a FixedString constant equals several String values, so an exact lookup declines';
SELECT count() FROM tab_s_primary_key WHERE v = toFixedString('ab', 4) SETTINGS force_primary_key = 1; -- { serverError INDEX_NOT_USED }
SELECT count() FROM tab_s_bloom_filter WHERE v = toFixedString('ab', 2) SETTINGS force_data_skipping_indices = 'idx'; -- { serverError INDEX_NOT_USED }
SELECT count() FROM tab_s_bloom_filter WHERE v IN (SELECT toFixedString('ab', 4)) SETTINGS force_data_skipping_indices = 'idx'; -- { serverError INDEX_NOT_USED }
SELECT count() FROM tab_s_text_array WHERE v = toFixedString('ab', 2) SETTINGS force_data_skipping_indices = 'idx'; -- { serverError INDEX_NOT_USED }

SELECT '-- Array and Map columns';
DROP TABLE IF EXISTS tab_array_string;
DROP TABLE IF EXISTS tab_array_fixed_string;
DROP TABLE IF EXISTS tab_map;
CREATE TABLE tab_array_string (k UInt32, a Array(String), INDEX idx a TYPE bloom_filter GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_array_string SELECT number, [['ab', 'ab\0', 'ab\0\0', 'zz'][number + 1]] FROM numbers(4);
CREATE TABLE tab_array_fixed_string (k UInt32, a Array(FixedString(4)), INDEX idx a TYPE bloom_filter GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_array_fixed_string SELECT number, [['ab', 'zz'][number + 1]] FROM numbers(2);
CREATE TABLE tab_map (k UInt32, m Map(FixedString(4), FixedString(4)), INDEX idx_keys mapKeys(m) TYPE bloom_filter GRANULARITY 1, INDEX idx_values mapValues(m) TYPE bloom_filter GRANULARITY 1) ENGINE = MergeTree ORDER BY k SETTINGS index_granularity = 1;
INSERT INTO tab_map SELECT number, map(['ab', 'zz'][number + 1], ['cd', 'yy'][number + 1]) FROM numbers(2);
SELECT 'tab_array_string', 'has(a, toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_array_string WHERE has(a, toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE has(a, toFixedString('ab', 2));
SELECT 'tab_array_string', 'hasAny(a, [toFixedString(\'ab\', 2)])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAny(a, [toFixedString('ab', 2)]) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAny(a, [toFixedString('ab', 2)]);
SELECT 'tab_array_string', 'hasAll(a, [toFixedString(\'ab\', 2)])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAll(a, [toFixedString('ab', 2)]) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAll(a, [toFixedString('ab', 2)]);
SELECT 'tab_array_string', 'indexOf(a, toFixedString(\'ab\', 2)) != 0', count() AS c, c = (SELECT count() FROM tab_array_string WHERE indexOf(a, toFixedString('ab', 2)) != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE indexOf(a, toFixedString('ab', 2)) != 0;
SELECT 'tab_array_string', 'arrayJoin(a) = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_array_string WHERE arrayJoin(a) = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE arrayJoin(a) = toFixedString('ab', 2);
SELECT 'tab_array_string', 'has(a, toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_array_string WHERE has(a, toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE has(a, toFixedString('ab', 6));
SELECT 'tab_array_string', 'hasAny(a, [toFixedString(\'ab\', 6)])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAny(a, [toFixedString('ab', 6)]) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAny(a, [toFixedString('ab', 6)]);
SELECT 'tab_array_string', 'hasAll(a, [toFixedString(\'ab\', 6)])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAll(a, [toFixedString('ab', 6)]) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAll(a, [toFixedString('ab', 6)]);
SELECT 'tab_array_string', 'indexOf(a, toFixedString(\'ab\', 6)) != 0', count() AS c, c = (SELECT count() FROM tab_array_string WHERE indexOf(a, toFixedString('ab', 6)) != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE indexOf(a, toFixedString('ab', 6)) != 0;
SELECT 'tab_array_string', 'arrayJoin(a) = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_array_string WHERE arrayJoin(a) = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE arrayJoin(a) = toFixedString('ab', 6);
SELECT 'tab_array_string', 'has(a, \'ab\')', count() AS c, c = (SELECT count() FROM tab_array_string WHERE has(a, 'ab') SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE has(a, 'ab');
SELECT 'tab_array_string', 'hasAny(a, [\'ab\'])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAny(a, ['ab']) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAny(a, ['ab']);
SELECT 'tab_array_string', 'hasAll(a, [\'ab\'])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAll(a, ['ab']) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAll(a, ['ab']);
SELECT 'tab_array_string', 'indexOf(a, \'ab\') != 0', count() AS c, c = (SELECT count() FROM tab_array_string WHERE indexOf(a, 'ab') != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE indexOf(a, 'ab') != 0;
SELECT 'tab_array_string', 'arrayJoin(a) = \'ab\'', count() AS c, c = (SELECT count() FROM tab_array_string WHERE arrayJoin(a) = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE arrayJoin(a) = 'ab';
SELECT 'tab_array_string', 'has(a, \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_array_string WHERE has(a, 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE has(a, 'ab\0');
SELECT 'tab_array_string', 'hasAny(a, [\'ab\\0\'])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAny(a, ['ab\0']) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAny(a, ['ab\0']);
SELECT 'tab_array_string', 'hasAll(a, [\'ab\\0\'])', count() AS c, c = (SELECT count() FROM tab_array_string WHERE hasAll(a, ['ab\0']) SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE hasAll(a, ['ab\0']);
SELECT 'tab_array_string', 'indexOf(a, \'ab\\0\') != 0', count() AS c, c = (SELECT count() FROM tab_array_string WHERE indexOf(a, 'ab\0') != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE indexOf(a, 'ab\0') != 0;
SELECT 'tab_array_string', 'arrayJoin(a) = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_array_string WHERE arrayJoin(a) = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_array_string WHERE arrayJoin(a) = 'ab\0';
SELECT 'tab_array_fixed_string', 'has(a, toFixedString(\'ab\', 2))', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE has(a, toFixedString('ab', 2)) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE has(a, toFixedString('ab', 2));
SELECT 'tab_array_fixed_string', 'hasAny(a, [toFixedString(\'ab\', 2)])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAny(a, [toFixedString('ab', 2)]) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAny(a, [toFixedString('ab', 2)]);
SELECT 'tab_array_fixed_string', 'hasAll(a, [toFixedString(\'ab\', 2)])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAll(a, [toFixedString('ab', 2)]) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAll(a, [toFixedString('ab', 2)]);
SELECT 'tab_array_fixed_string', 'indexOf(a, toFixedString(\'ab\', 2)) != 0', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE indexOf(a, toFixedString('ab', 2)) != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE indexOf(a, toFixedString('ab', 2)) != 0;
SELECT 'tab_array_fixed_string', 'arrayJoin(a) = toFixedString(\'ab\', 2)', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE arrayJoin(a) = toFixedString('ab', 2) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE arrayJoin(a) = toFixedString('ab', 2);
SELECT 'tab_array_fixed_string', 'has(a, toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE has(a, toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE has(a, toFixedString('ab', 6));
SELECT 'tab_array_fixed_string', 'hasAny(a, [toFixedString(\'ab\', 6)])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAny(a, [toFixedString('ab', 6)]) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAny(a, [toFixedString('ab', 6)]);
SELECT 'tab_array_fixed_string', 'hasAll(a, [toFixedString(\'ab\', 6)])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAll(a, [toFixedString('ab', 6)]) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAll(a, [toFixedString('ab', 6)]);
SELECT 'tab_array_fixed_string', 'indexOf(a, toFixedString(\'ab\', 6)) != 0', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE indexOf(a, toFixedString('ab', 6)) != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE indexOf(a, toFixedString('ab', 6)) != 0;
SELECT 'tab_array_fixed_string', 'arrayJoin(a) = toFixedString(\'ab\', 6)', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE arrayJoin(a) = toFixedString('ab', 6) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE arrayJoin(a) = toFixedString('ab', 6);
SELECT 'tab_array_fixed_string', 'has(a, \'ab\')', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE has(a, 'ab') SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE has(a, 'ab');
SELECT 'tab_array_fixed_string', 'hasAny(a, [\'ab\'])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAny(a, ['ab']) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAny(a, ['ab']);
SELECT 'tab_array_fixed_string', 'hasAll(a, [\'ab\'])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAll(a, ['ab']) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAll(a, ['ab']);
SELECT 'tab_array_fixed_string', 'indexOf(a, \'ab\') != 0', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE indexOf(a, 'ab') != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE indexOf(a, 'ab') != 0;
SELECT 'tab_array_fixed_string', 'arrayJoin(a) = \'ab\'', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE arrayJoin(a) = 'ab' SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE arrayJoin(a) = 'ab';
SELECT 'tab_array_fixed_string', 'has(a, \'ab\\0\')', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE has(a, 'ab\0') SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE has(a, 'ab\0');
SELECT 'tab_array_fixed_string', 'hasAny(a, [\'ab\\0\'])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAny(a, ['ab\0']) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAny(a, ['ab\0']);
SELECT 'tab_array_fixed_string', 'hasAll(a, [\'ab\\0\'])', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE hasAll(a, ['ab\0']) SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE hasAll(a, ['ab\0']);
SELECT 'tab_array_fixed_string', 'indexOf(a, \'ab\\0\') != 0', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE indexOf(a, 'ab\0') != 0 SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE indexOf(a, 'ab\0') != 0;
SELECT 'tab_array_fixed_string', 'arrayJoin(a) = \'ab\\0\'', count() AS c, c = (SELECT count() FROM tab_array_fixed_string WHERE arrayJoin(a) = 'ab\0' SETTINGS use_skip_indexes = 0) FROM tab_array_fixed_string WHERE arrayJoin(a) = 'ab\0';
SELECT 'tab_map', 'mapContainsKey(m, \'ab\')', count() AS c, c = (SELECT count() FROM tab_map WHERE mapContainsKey(m, 'ab') SETTINGS use_skip_indexes = 0) FROM tab_map WHERE mapContainsKey(m, 'ab');
SELECT 'tab_map', 'mapContainsKey(m, toFixedString(\'ab\', 6))', count() AS c, c = (SELECT count() FROM tab_map WHERE mapContainsKey(m, toFixedString('ab', 6)) SETTINGS use_skip_indexes = 0) FROM tab_map WHERE mapContainsKey(m, toFixedString('ab', 6));
SELECT 'tab_map', 'm[\'ab\'] = \'cd\'', count() AS c, c = (SELECT count() FROM tab_map WHERE m['ab'] = 'cd' SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m['ab'] = 'cd';
SELECT 'tab_map', 'm[toFixedString(\'ab\', 2)] = \'cd\\0\'', count() AS c, c = (SELECT count() FROM tab_map WHERE m[toFixedString('ab', 2)] = 'cd\0' SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m[toFixedString('ab', 2)] = 'cd\0';
SELECT 'tab_map', 'm[\'ab\'] IN (\'cd\', \'xx\')', count() AS c, c = (SELECT count() FROM tab_map WHERE m['ab'] IN ('cd', 'xx') SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m['ab'] IN ('cd', 'xx');
SELECT 'tab_map', 'm[\'ab\'] IN (SELECT toFixedString(\'cd\', 6))', count() AS c, c = (SELECT count() FROM tab_map WHERE m['ab'] IN (SELECT toFixedString('cd', 6)) SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m['ab'] IN (SELECT toFixedString('cd', 6));
SELECT 'tab_map', 'm[\'xx\'] = \'\'', count() AS c, c = (SELECT count() FROM tab_map WHERE m['xx'] = '' SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m['xx'] = '';
SELECT 'tab_map', 'm[\'xx\'] = toFixedString(\'\', 2)', count() AS c, c = (SELECT count() FROM tab_map WHERE m['xx'] = toFixedString('', 2) SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m['xx'] = toFixedString('', 2);
SELECT 'tab_map', 'm[\'xx\'] IN (SELECT \'\\0\')', count() AS c, c = (SELECT count() FROM tab_map WHERE m['xx'] IN (SELECT '\0') SETTINGS use_skip_indexes = 0) FROM tab_map WHERE m['xx'] IN (SELECT '\0');
SELECT 'tab_map', 'mapContainsValue(m, \'cd\\0\')', count() AS c, c = (SELECT count() FROM tab_map WHERE mapContainsValue(m, 'cd\0') SETTINGS use_skip_indexes = 0) FROM tab_map WHERE mapContainsValue(m, 'cd\0');

DROP TABLE tab_s_primary_key;
DROP TABLE tab_s_minmax;
DROP TABLE tab_s_set;
DROP TABLE tab_s_bloom_filter;
DROP TABLE tab_s_tokenbf_v1;
DROP TABLE tab_s_ngrambf_v1;
DROP TABLE tab_s_text_array;
DROP TABLE tab_s_text_splitByNonAlpha;
DROP TABLE tab_f_primary_key;
DROP TABLE tab_f_minmax;
DROP TABLE tab_f_set;
DROP TABLE tab_f_bloom_filter;
DROP TABLE tab_f_tokenbf_v1;
DROP TABLE tab_f_ngrambf_v1;
DROP TABLE tab_f_text_array;
DROP TABLE tab_f_text_splitByNonAlpha;
DROP TABLE tab_array_string;
DROP TABLE tab_array_fixed_string;
DROP TABLE tab_map;
